services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wp_files:/var/www/html
    container_name: nginx
    restart: on-failure
  mariadb:
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    expose:
      - 3306
    env_file:
      - ./.env
    volumes:
      - wp_db:/var/lib/mysql
    container_name: mariadb
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    expose:
      - 9000
    volumes:
      - wp_file:/var/www/html
    container_name: wordpress

volumes:
  wp_db:
  wp_files: