services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wp_files:/var/www/html
    container_name: nginx
    networks:
      - inception
  mariadb:
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    expose:
      - 3306
    env_file:
      - ./.env
    volumes:
      - wp_db:/var/lib/mysql
    container_name: mariadb
    networks:
      - inception
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - nginx
    expose:
      - 9000
    volumes:
      - wp_files:/var/www/html
    container_name: wordpress
    networks:
      - inception

volumes:
  wp_db:
    name: wp_db
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/Users/hbouhsis/Desktop/wp_db_folder"
  wp_files:
    name: wp_files
    driver: local
    driver_opts:
      o: bind 
      type: none
      device: "/Users/hbouhsis/Desktop/wp_files_folder"

networks:
  inception:
    driver: bridge